### ISSUE TITLE
Where can rationale for moving this chart here be found?

### ISSUE THREAD

**Issue by AndrewSav** [grafana/helm2-grafana#2]
I'd like to know the reason behind the move and also why this was "downgraded" from helm 3 to helm 2 the chart in the old repo was working fine with helm 3. Thank you in advance,

**Comment by buildmaster** [comment]
the central repository is depreciated:
https://github.com/helm/charts#status-of-the-project
![Screen Shot 2020-09-04 at 12 12 07 PM](https://user-images.githubusercontent.com/19946/92185401-fd9b8b80-eea7-11ea-8593-9404cc374620.png)
so I'm guessing this is the first step of moving to grafana maintained charts.
